name: Master Build with JPackage

on:
  push:
    branches: [ master ] 

env:
  pkg-assembly: 'GTEngineGrapher.jar'
  pkg-name: 'gtenginegrapher'
  pkg-version: '1.2.1'

jobs:
  fat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.2'
        java-package: jdk
        architecture: x64
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Assemble Uberjar
      run: sbt assembly
    - name: Upload Uberjar
      uses: actions/upload-artifact@v4
      with:
        name: jars
        path: "${{ env.pkg-assembly }}"
  osx:
    needs: fat
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.2'
        java-package: jdk
        architecture: x64
    - name: Download fat jar
      uses: actions/download-artifact@v4
      with:
        name: jars
        path: artifacts
    - name: Package JAR as App Image
      run: 'jpackage --name ${{ env.pkg-name }} --type app-image --input ./artifacts --dest ./AppImage --name GTEngineGrapher --main-class gtenginegrapher.Main --main-jar ${{ env.pkg-assembly }} --app-version ${{ env.pkg-version }}'
    - name: View artifacts
      run: ls
    - name: Upload OSX App Image
      uses: actions/upload-artifact@v4
      with:
        name: appimage-osx
        path: "./AppImage/GTEngineGrapher"
  windows:
    needs: fat
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.2'
        java-package: jdk
        architecture: x64
    - name: Download fat jar
      uses: actions/download-artifact@v4
      with:
        name: jars
        path: artifacts
    - name: Package JAR as App Image
      run: 'jpackage --name ${{ env.pkg-name }} --type app-image --input .\\artifacts --dest .\\AppImage --name GTEngineGrapher --main-class gtenginegrapher.Main --main-jar ${{ env.pkg-assembly }} --win-console --app-version ${{ env.pkg-version }}'
    - name: View artifacts
      run: dir
    - name: Upload Windows App Image
      uses: actions/upload-artifact@v4
      with:
        name: appimage-windows
        path: ".\\AppImage\\GTEngineGrapher"
  linux:
    needs: fat
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.2'
        java-package: jdk
        architecture: x64
    - name: Download fat jar
      uses: actions/download-artifact@v4
      with:
        name: jars
        path: artifacts
    - name: Package JAR as App Image
      run: 'jpackage --name ${{ env.pkg-name }} --type app-image --input ./artifacts --dest ./AppImage --name GTEngineGrapher --main-class gtenginegrapher.Main --main-jar ${{ env.pkg-assembly }} --app-version ${{ env.pkg-version }}'
    - name: View artifacts
      run: ls
    - name: Upload Linux App Image
      uses: actions/upload-artifact@v4
      with:
        name: appimage-linux
        path: "./AppImage/GTEngineGrapher"
